### ISSUE TITLE
sherpa instrument-map weight code broken by sherpa updates

### ISSUE THREAD

**Issue by DougBurke** [cxcsds/ciao-contrib#315]
Looks like I need to update `sherpa_contrib.utils.get_instmap_weights` to account for sherpa/sherpa#614 since the tests now fail:

```
% python test_weights.py 
EEEEEEEEEE..EEE
======================================================================
ERROR: test_estimate1 (__main__.TestSimple)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_weights.py", line 161, in test_estimate1
    wgt = utils.get_instmap_weights()
  File "/home/dburke/anaconda3/envs/ciao412-py37/lib/python3.7/site-packages/sherpa_contrib/utils.py", line 600, in get_instmap_weights
    return InstMapWeights1DInt(id, fluxtype=fluxtype)
  File "/home/dburke/anaconda3/envs/ciao412-py37/lib/python3.7/site-packages/sherpa_contrib/utils.py", line 142, in __init__
    self._apply_mask(d)
  File "/home/dburke/anaconda3/envs/ciao412-py37/lib/python3.7/site-packages/sherpa_contrib/utils.py", line 192, in _apply_mask
    m = data._get_mask()
AttributeError: 'Data1DInt' object has no attribute '_get_mask'

...
```

**Comment by DougBurke** [comment]
Hmm. This has been fixed as of #269 - need to get the updated code to DS I guess!
