### ISSUE TITLE
4.12: check_ciao_version

### ISSUE THREAD

**Issue by kglotfelty** [cxcsds/ciao-contrib#321]
@DougBurke  -- I'm getting an error when I try to run `check_ciao_version` in the class-ciao 4.12b2b, Linux.

```bash
% check_ciao_version --debug
# check_ciao_version (11 June 2019): ERROR 'HTTPResponse' object has no attribute 'decode'


##### Traceback:

Traceback (most recent call last):
  File "/export/CIAOT/ciaot_install/20191113/ciao-4.12/contrib/lib/python3.5/site-packages/ciao_contrib/logger_wrapper.py", line 531, in new_fn
    return fn(*args, **kw)
  File "/export/CIAOT/ciaot_install/20191113/ciao-4.12/contrib/bin/check_ciao_version", line 241, in doit
    latest = versioninfo.get_latest_versions()
  File "/export/CIAOT/ciaot_install/20191113/ciao-4.12/contrib/lib/python3.5/site-packages/ciao_contrib/_tools/versioninfo.py", line 254, in get_latest_versions
    contents = cts.decode('utf8')
AttributeError: 'HTTPResponse' object has no attribute 'decode'

% git log -1
commit d555f795504fc801ace985e6cca6b8af903c80d5 (HEAD -> master, origin/master, origin/HEAD)
Merge: 11c4a23 daf4255
Author: Doug Burke <dburke.gw@gmail.com>
Date:   Tue Nov 19 06:47:50 2019 -0500

    Merge pull request #318 from kglotfelty/csc_https
    
    Csc https
```

The conda install doesn't work because of the change in `VERSION_*` files [known].

**Comment by kglotfelty** [comment]
Oddly on mac I'm getting a different error

```bash
% check_ciao_version --debug 
# check_ciao_version (11 June 2019): ERROR Unable to parse line: '<HTML>'


##### Traceback:

Traceback (most recent call last):
  File "/Users/kjg/CIAOT/ciaot_install/20191113/ciao-4.12/contrib/lib/python3.5/site-packages/ciao_contrib/logger_wrapper.py", line 531, in new_fn
    return fn(*args, **kw)
  File "/Users/kjg/CIAOT/ciaot_install/20191113/ciao-4.12/contrib/bin/check_ciao_version", line 241, in doit
    latest = versioninfo.get_latest_versions()
  File "/Users/kjg/CIAOT/ciaot_install/20191113/ciao-4.12/contrib/lib/python3.5/site-packages/ciao_contrib/_tools/versioninfo.py", line 255, in get_latest_versions
    return parse_version_file(contents.splitlines())
  File "/Users/kjg/CIAOT/ciaot_install/20191113/ciao-4.12/contrib/lib/python3.5/site-packages/ciao_contrib/_tools/versioninfo.py", line 119, in parse_version_file
    raise IOError("Unable to parse line: '{0}'".format(l))
OSError: Unable to parse line: '<HTML>'
```

**Comment by DougBurke** [comment]
Ta - I changed some stuff to use our "standard" fallback code for downloading (which is probably not really needed anymore, but ...) and have obviously not tested it out suffiicently.

**Comment by DougBurke** [comment]
So, the <HTML> thing is that it the new "fallback to wget/curl on error" behavior (from the changeover to the standard "download" routine) is conflicting with the existing code which 

  - tries to download a system-specific version file
  - falls over to the generic file if not found

So there's confusion over a 404 and what gets returned (now get an error page which wget/curl returns the contents of).

I think I'm just going to go back to the python-only download code for this case, and rely on SSL now being supported on the platforms we support. Or maybe some other inspiration will strike.
