### ISSUE TITLE
chandra_repro: newasol issue

### ISSUE THREAD

**Issue by DougBurke** [cxcsds/ciao-contrib#47]
Is this a "problematic" obsid?

```
% ciaover -v | egrep 'Contrib|CIAO'
  CIAO        : CIAO 4.9 Friday, December  2, 2016
  Contrib     : Package release 3  Wednesday, May 24, 2017
CIAO Installation: LinuxUP3
% punlearn chandra_repro
% chandra_repro 2469 --debug
Output directory (default = $indir/repro) (): 

Processing input directory '/home/djburke/data/moon/2469'

# chandra_repro (06 March 2017): ERROR local variable 'newasol' referenced before assignment


##### Traceback:

Traceback (most recent call last):
  File "/home/djburke/local/u35/ciao-4.9/contrib/lib/python3.5/site-packages/ciao_contrib/logger_wrapper.py", line 531, in new_fn
    return fn(*args, **kw)
  File "/home/djburke/local/u35/ciao-4.9/contrib/bin/chandra_repro", line 2224, in chandra_repro
    main_body(p)
  File "/home/djburke/local/u35/ciao-4.9/contrib/bin/chandra_repro", line 2166, in main_body
    pars = get_inputs(pars)
  File "/home/djburke/local/u35/ciao-4.9/contrib/bin/chandra_repro", line 863, in get_inputs
    link_or_copy(newasol, path)
UnboundLocalError: local variable 'newasol' referenced before assignment
```

**Comment by kglotfelty** [comment]
Just a little bit ... there is no aspect solution.

This is one of the "primary_obc" datasets that relies on the osol.

Of course should error out a bit more nicely.

**Comment by kglotfelty** [comment]
So the bad assignment is a 5+ yr old bug -- unrelated to the on-board aspect solution.  That's an easy fix.

```diff
diff --git a/ciao-4.9/contrib/bin/chandra_repro b/ciao-4.9/contrib/bin/chandra_repro
index 6523c02..3de19f3 100755
--- a/ciao-4.9/contrib/bin/chandra_repro
+++ b/ciao-4.9/contrib/bin/chandra_repro
@@ -860,7 +860,7 @@ def get_inputs(params):
                 newbias = gunzip(params["secondarydir"] + ff)
 
                 path=os.path.join(params["outdir"], os.path.basename(newbias))
-                link_or_copy(newasol, path)
+                link_or_copy(newbias, path)
   
                 uff=ff.split(".gz")[0]
                 params["cleanup_files"].append(os.path.join(params["outdir"], uff))
```




But, getting past that,  we then hit the problem with no aspect solution

```bash
$ chandra_repro 2469 goo clob+

Processing input directory '/stage/pool1/kjg/2469'


Cleaning up intermediate files

Could not locate asol1 fits file(s) in: /stage/pool1/kjg/2469/primary/
# chandra_repro (06 March 2017): ERROR input error
```

Now, even if we do try to fix this(*), there will still be the problem that the L2 event file will have 0 events and 0 good time.

```bash
$ dmlist 2469/secondary/acisf02469_001N004_flt1.fits subspace | grep time
   1 time                 Real8               NULL
```

because of the moon-angle (or earth angle for those observations) violations in the mission time line.

So we might want to think what we want to do here.  Recomputing the MTL limits to drop the moon (earth) angle constraint would be possible but definitely beyond the scope of what chandra_repro is currently doing.


(*) Notes on changes needed:

- We can trigger off the `ASPTYPE="OBC"` keyword in the evt1 file to know to glob+re for the `osol` rather than the `asol` files.
- The `osol` files are in the `secondary/aspect` directory which is new territory for chandra_repro.

**Comment by DougBurke** [comment]
So there's a simple fix for the error message, and then a more-complicated issue to decide how to handle asol-less observations?

**Comment by DougBurke** [comment]
And, for the asol-less case, I assume this is larger than just `chandra_repro`, since other scripts - such as `merge/reproject/flux_obs` and `specextract` would need to handle this case ?

**Comment by kglotfelty** [comment]
Correct.  There is a simple fix to the typo, that will then let the more informative exception be thrown.

**Comment by kglotfelty** [comment]
Well, the `ASOLFILE` keyword does point to the `osol` file.  The only real gotcha is that is lives in `secondary/aspect` directory.  So there may be some kind of change to the search paths but otherwise might be minimal.

      Note:  There are other observations w/ asol files that still have 0 
      good time for other reasons.

The only OBC observations are earth+moon observations.  [Ignoring the doors-opening "cal" target]

```bash
% dmlist obspar_20170523.fits"[obi_data=primary_obc][cols obs_id,date-obs,observer,object]" data,clean
#  obs_id   date-obs               observer                                           object
 1264     1999-08-14T12:26:50    DR. CXC CALIBRATION                                PKS0637-752                                          
 2468     2001-09-22T07:01:49    DR. SCOTT WOLK                                     DARK MOON                                            
 2469     2001-07-26T02:00:00    DR. SCOTT WOLK                                     DARK MOON                                            
 2487     2001-07-26T02:54:41    DR. SCOTT WOLK                                     DARK MOON                                            
 2488     2001-07-26T04:07:34    DR. SCOTT WOLK                                     DARK MOON                                            
 2489     2001-07-26T05:01:10    DR. SCOTT WOLK                                     DARK MOON                                            
 2490     2001-07-26T06:13:48    DR. SCOTT WOLK                                     DARK MOON                                            
 2493     2001-07-26T07:07:49    DR. SCOTT WOLK                                     DARK MOON                                            
 3368     2001-09-22T08:00:04    DR. SCOTT WOLK                                     DARK MOON                                            
 3370     2001-09-22T09:00:22    DR. SCOTT WOLK                                     DARK MOON                                            
 3371     2001-09-22T10:30:03    DR. SCOTT WOLK                                     DARK MOON                                            
 4410     2003-02-07T01:24:19    DR. G. GLADSTONE                                   EARTH                                                
 4456     2003-12-16T04:14:59    Dr. Ronald Elsner                                  EARTH                                                
 4457     2004-01-06T07:57:26    Dr. Ronald Elsner                                  EARTH                                                
 4458     2004-02-28T05:01:33    Dr. Ronald Elsner                                  EARTH                                                
 4459     2004-01-24T20:01:25    Dr. Ronald Elsner                                  EARTH                                                
 4460     2004-01-30T03:06:20    Dr. Ronald Elsner                                  EARTH                                                
 4461     2004-02-14T23:58:05    Dr. Ronald Elsner                                  EARTH                                                
 4462     2004-03-04T12:04:49    Dr. Ronald Elsner                                  EARTH                                                
 4463     2004-03-07T03:32:21    Dr. Ronald Elsner                                  EARTH                                                
 4464     2004-04-10T12:28:18    Dr. Ronald Elsner                                  EARTH                                                
 4465     2004-04-13T03:46:20    Dr. Ronald Elsner                                  EARTH                                                
 5311     2004-05-04T04:37:41    Dr. Jeremy Drake                                   Moon                                                 
 5312     2004-06-02T08:40:45    Dr. Jeremy Drake                                   Moon                                                 
 5324     2004-05-04T07:00:12    Dr. Jeremy Drake                                   Moon                                                 
 5327     2004-06-02T10:59:15    Dr. Jeremy Drake                                   Moon                                                 
 5351     2004-07-27T23:13:46    Dr. Jeremy Drake                                   Moon                                                 
 5352     2004-07-28T01:30:35    Dr. Jeremy Drake                                   Moon                        
 ```

but even getting past this -- at least for  2469, all the interesting moon-events are grade=7 so they are get filtered out.

**Comment by DougBurke** [comment]
Just to note that *my* interest in the moon observations is for "ohhh, I'd like to make an image of the moon for the public" rather than scientific, but it does point to a gap in our code and documentation.

**Comment by kglotfelty** [comment]
I'm going to split this issue.  I've been looking at the effects of fixing this _newasol_ issue which affects all datasets 

      It only really affects a handful of datasets, but the fact that the bias files were not 
      copied to the input dir does mean that the bright/dim badpixel checks haven't 
      done for any obs -- but only a few obs have this issue.

The issue of what to do with `PRIMARY_OBC` mode datasets is bigger and as was pointed out, affects multiple scripts.
