### ISSUE TITLE
make_instmap_weights update for sherpa 

### ISSUE THREAD

**Issue by kglotfelty** [cxcsds/ciao-contrib#487]
@DougBurke 

It looks like one of the sherpa PRs removes|changes one of the `imports` that make_instmap_weights uses

https://github.com/cxcsds/ciao-contrib/blob/83ae83e8cb55b97770d74ed1e52cc194015ced1e/sherpa_contrib/utils.py#L54

```diff
<  Solar Abundance Vector set to angr:  Anders E. & Grevesse N. Geochimica et Cosmochimica Acta 53, 197 (1989)
<  Cross Section Table set to vern:  Verner, Ferland, Korista, and Yakovlev 1996
< Model used: 
< (xsphabs.abs1 * powlaw1d.p1)
<    Param        Type          Value          Min          Max      Units
<    -----        ----          -----          ---          ---      -----
<    abs1.nH      thawed          2.2            0       100000 10^22 atoms / cm^2
<    p1.gamma     thawed          1.6          -10           10           
<    p1.ref       frozen            1 -3.40282e+38  3.40282e+38           
<    p1.ampl      thawed            1            0  3.40282e+38           
< Created: PWD/weights.txt
---
> Traceback (most recent call last):
>   File "INSTALL/contrib/bin/make_instmap_weights", line 44, in <module>
>     from sherpa_contrib.utils import save_instmap_weights
>   File "INSTALL/contrib/lib/python3.8/site-packages/sherpa_contrib/utils.py", line 54, in <module>
>     from sherpa.astro.utils import _charge_e
> ImportError: cannot import name '_charge_e' from 'sherpa.astro.utils' (INSTALL/lib/python3.8/site-packages/sherpa/astro/utils/__init__.py)
> tool returns non-zero exit status
```

This is with the 2021-07-07 CIAOX

**Comment by DougBurke** [comment]
Yes, this is all @hamogu 's fault in https://github.com/sherpa/sherpa/pull/1178 - we'll need to change the line to

```python
from sherpa.astro import charge_e
```

but this is a CIAO 4.14-only changhe
