### ISSUE TITLE
find_chandra_obsid with unicode

### ISSUE THREAD

**Issue by kglotfelty** [cxcsds/ciao-contrib#695]
Hi,

I'm assuming that this is because the PI name/Observer has a unicode characters:

```bash
% find_chandra_obsid 27566 verb=5 --debug
Running: find_chandra_obsid
  version: 27 January 2022
Looking for position of ObsId 27566
Trying to identify obsid=27566
Retrieving URL: https://cda.harvard.edu/srservices/ocatDetails.do?obsid=27566&format=text timeout=None
# find_chandra_obsid (27 January 2022): ERROR 'utf-8' codec can't decode byte 0xfc in position 1674: invalid start byte


##### Traceback:

Traceback (most recent call last):
  File "/export/CIAOT/ciaot_install/20221019/ciao-4.15/contrib/lib/python3.9/site-packages/ciao_contrib/logger_wrapper.py", line 560, in new_fn
    return fn(*args, **kw)
  File "/export/CIAOT/ciaot_install/20221019/ciao-4.15/contrib/bin/find_chandra_obsid", line 579, in fco
    run_fco(opts)
  File "/export/CIAOT/ciaot_install/20221019/ciao-4.15/contrib/bin/find_chandra_obsid", line 529, in run_fco
    pos = find_obsid_position(name)
  File "/export/CIAOT/ciaot_install/20221019/ciao-4.15/contrib/bin/find_chandra_obsid", line 483, in find_obsid_position
    ans = retrieve_url(url).read().decode('utf8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfc in position 1674: invalid start byte
```

which suggests the DB isn't using UTF-8 .... wonder what they are using?

**Comment by kglotfelty** [comment]
looks like maybe it's `ISO-8859`

```bash
% wget -q -Ofoo "https://cda.harvard.edu/srservices/ocatDetails.do?obsid=27566&format=text"
% file foo                                                       
foo: ISO-8859 text, with very long lines
```

**Comment by DougBurke** [comment]
Hmm, using "iso-8859" rather than "utf-8" just gets the code to complain it's an unknown encoding. Bah. It needs to be "iso-8859-1". Because.

```
% find_chandra_obsid 27566 
# obsid  sepn   inst grat   time    obsdate   piname                        target
27566     0.0 ACIS-S NONE    9.9 2022-11-21 Ag++eros "Gaia DR2 125343573948444800"
```

That's not the nicest way to show this name....

**Comment by kglotfelty** [comment]
What about iso8859 (no dash)? I think I remember trying that but I don't
remember what the output looked like.

**Comment by DougBurke** [comment]
Hmm. The "Ag++eros" part is coming from the footprint server. But we're parsing the response via an XML parser, and

```
% curl 'https://cxcfps.cfa.harvard.edu/cgi-bin/cda/footprint/get_vo_table.pl?strict=1&POS=48.26170833333333,32.89640277777778&SIZE=0.016666666666666666' > foo
% file foo
foo: XML 1.0 document, ASCII text, with very long lines, with no line terminators
```

suggests that it's the footprint service that is changing the name, so nothing we can do.
