### ISSUE TITLE
crates_contrib/utils.py issue with Python 3.10

### ISSUE THREAD

**Issue by nplee** [cxcsds/ciao-contrib#699]
This comes from regression test 'coords 01' where it fails on a Conda CIAO installation on Python 3.10, with the error:

```
Traceback (most recent call last):
  File "CT_INPUT/coords/trace_hrc.py", line 70, in <module>
    write_columns( outfile, output, colnames=['time',xcolumn,ycolumn], 
  File "INSTALL/lib/python3.10/site-packages/crates_contrib/utils.py", line 510, in write_columns
    cr = make_table_crate(*args, **kwargs)
  File "INSTALL/lib/python3.10/site-packages/crates_contrib/utils.py", line 339, in make_table_crate
    isdict = isinstance(args[0], collections.Mapping)
AttributeError: module 'collections' has no attribute 'Mapping'
tool returns non-zero exit status
```

It looks like `Mapping` was deprecated from `collections` in 3.10 and moved to `collections.abc`.  I think the simplest solution  is updating line 339 of `crates_contrib/utils.py` from:

```
isdict = isinstance(args[0], collections.Mapping)
```
to:
```
try:
     isdict = isinstance(args[0], collections.Mapping)
except AttributeError:
     isdict = isinstance(args[0], collections.abc.Mapping)
```

**Comment by kglotfelty** [comment]
it looks like the only contrib script that uses `write_columns` is the `monitor_photom` script.  It's regression test runs OK so it must not hit this code path.
