### ISSUE TITLE
runtool problem storing INDEF in python3?

### ISSUE THREAD

**Issue by kglotfelty** [cxcsds/ciao-contrib#70]
I ran into a problem using `csmooth` via `runtool` in Python3.  I think it's related to the `INDEF` values.

In Python2, I can:

```python
>>> from ciao_contrib.runtool import make_tool
>>> csmooth = make_tool("csmooth")
>>> csmooth('img.fits', outfile='/pool1/kjg/csm', sclmap='', outsigfile='',  outsclfile="", conmeth="fft", conkerneltype='gaus', sigmin=3, sigmax=5, sclmin='INDEF', sclmax=str(5),  sclmode="compute",clobber=True)
```
and it works fine.  

In Python3, I get:

```python
>>> from ciao_contrib.runtool import make_tool
>>> csmooth = make_tool("csmooth")
>>> csmooth('img.fits', outfile='/pool1/kjg/csm', sclmap='', outsigfile='',  outsclfile="", conmeth="fft", conkerneltype='gaus', sigmin=3, sigmax=5, sclmin='INDEF', sclmax=str(5),  sclmode="compute",clobber=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/export/ciao-4.9-python3/ciao-4.9/contrib/lib/python3.5/site-packages/ciao_contrib/runtool.py", line 1806, in __call__
    self._process_argument_list(args, kwargs)
  File "/export/ciao-4.9-python3/ciao-4.9/contrib/lib/python3.5/site-packages/ciao_contrib/runtool.py", line 1700, in _process_argument_list
    self._validate(pname, pval, store=True)
  File "/export/ciao-4.9-python3/ciao-4.9/contrib/lib/python3.5/site-packages/ciao_contrib/runtool.py", line 1018, in _validate
    if not self._check_param_limit(pname, pval, pinfo.lo, operator.gt):
  File "/export/ciao-4.9-python3/ciao-4.9/contrib/lib/python3.5/site-packages/ciao_contrib/runtool.py", line 1649, in _check_param_limit
    return pval == lim or op(pval, lim)
TypeError: unorderable types: float() > NoneType()
```

if I replace the `sclmin='INDEF'` with a value, then it runs all the way through.

**Comment by DougBurke** [comment]
Thanks for the report. If I remember correctly I map between `'INDEF'` and `None` for the Parameter/Python worlds, so probably just need to explicitly handle the `None` case in the validation code.

**Comment by DougBurke** [comment]
Aha, running with logging set to a verbosity of 5 points out that the problem is that sclmax has a minimum value of ")sclmin", but sclmin is INDEF/None which I must not be handling properly:

```
Entering _validate for name=sigmax val=5 (type=<class 'int'>) store=True
Validating csmooth.sigmax val=5 as a float
Validating csmooth.sigmax val=5.0 against min/max=)sigmin/None
Expanding redirect: input=)sigmin
 -> 3.0
Setting csmooth.sigmax to 5.0 (<class 'float'>)
Setting parameter sclmin to INDEF [from <class 'str'>]
Entering _validate for name=sclmin val=INDEF (type=<class 'str'>) store=True
Validating csmooth.sclmin val=INDEF as a float
Setting csmooth.sclmin to None (<class 'NoneType'>)
Setting parameter sclmax to 5 [from <class 'str'>]
Entering _validate for name=sclmax val=5 (type=<class 'str'>) store=True
Validating csmooth.sclmax val=5 as a float
Validating csmooth.sclmax val=5.0 against min/max=)sclmin/None
Expanding redirect: input=)sclmin
 -> None
... and this is where the error happens ...
```
