### ISSUE TITLE
RFE: ObsInfo support images

### ISSUE THREAD

**Issue by kglotfelty** [cxcsds/ciao-contrib#74]
It looks like the ObsInfo class only supports tables?  If we're just getting keywords from the file, can't we also support images?

This works:

```bash
% python -c 'from ciao_contrib._tools.obsinfo import ObsInfo;print(ObsInfo("/soft/ciao/test/smoke/data/acisf04425_000N003_evt1.fits"))'
ObsInfo: file=/soft/ciao/test/smoke/data/acisf04425_000N003_evt1.fits ObsId=4425
```

but this fails:

```bash
% python -c 'from ciao_contrib._tools.obsinfo import ObsInfo;print(ObsInfo("/soft/ciao/test/smoke/data/acisf04425_000N003_evt1.fits[bin sky=32]"))'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/export/ciao-4.9/contrib/lib/python2.7/site-packages/ciao_contrib/_tools/obsinfo.py", line 102, in __init__
    raise IOError("{} is an image, not a table!".format(infile))
IOError: /soft/ciao/test/smoke/data/acisf04425_000N003_evt1.fits[bin sky=32] is an image, not a table!
```

[From JCM's ciaodoc 8/29/2017 email re: simulate_psf parameter file.]

**Comment by kglotfelty** [comment]
Reviewing `ObsInfo`, it is also wants to read the ccd_id column of the input file to determine which chips are present in the dataset.  This doesn't work so well for images.

I'll leave this here for now, but it looks like my issue with `simulate_psf` can be addressed by using the `find_ancillary_files_crate` routine instead since `simulate_psf` is only looking to locate the asol|msk files.    

Or, I'm happy to close this.
