### ISSUE TITLE
obsid_search_csc user error leads to odd error

### ISSUE THREAD

**Issue by DougBurke** [cxcsds/ciao-contrib#760]
```
% obsid_search_csc 21355 outfile= columns=o.region_id,o,sat_src_flag,o.cnts_aper_n,o.flux_significance_b,o.hard_hm,o.hard_ms cat=current
...
# obsid_search_csc (20 September 2022): ERROR list index out of range
```

There's at least two errors here: 

- o.cnts_aper_n is wrong, but we don't catch this because
- I say "o,sat_src_flag" rather than "o.sat_src_flag" which is presumably the cause of the error

The debug output is

```
% obsid_search_csc 3041 outfile= columns=o,sat_src_flag cat=current --debug
obsid_search_csc
           obsid = 3041
         outfile = 
         columns = o,sat_src_flag
        download = none
            root = ./
           bands = broad,wide
       filetypes = regevt,pha,arf,rmf,lc,psf,regexp
         catalog = current
         verbose = 1
         clobber = no
            mode = ql

# obsid_search_csc (20 September 2022): ERROR list index out of range


##### Traceback:

Traceback (most recent call last):
  File "/home/dburke/miniconda3/envs/ciao415-py310/lib/python3.10/site-packages/ciao_contrib/logger_wrapper.py", line 560, in new_fn
    return fn(*args, **kw)
  File "/home/dburke/miniconda3/envs/ciao415-py310/bin/obsid_search_csc", line 112, in main
    pp = parse_inputs( pars )
  File "/home/dburke/miniconda3/envs/ciao415-py310/bin/obsid_search_csc", line 55, in parse_inputs
    retval["columns"] = csc.check_required_names( retval["columns"], pars["catalog"] )
  File "/home/dburke/miniconda3/envs/ciao415-py310/lib/python3.10/site-packages/ciao_contrib/cda/csccli.py", line 1406, in check_required_names
    c2 = expand_standard_cols( cols, cat_version )
  File "/home/dburke/miniconda3/envs/ciao415-py310/lib/python3.10/site-packages/ciao_contrib/cda/csccli.py", line 1395, in expand_standard_cols
    append_cols_check_conflict( retval, cc )
  File "/home/dburke/miniconda3/envs/ciao415-py310/lib/python3.10/site-packages/ciao_contrib/cda/csccli.py", line 1334, in append_cols_check_conflict
    if "m.{}".format(vv[1]) in retval:
IndexError: list index out of range
```

**Comment by kglotfelty** [comment]
This is closed with #764.
