### ISSUE TITLE
find_chandra_obsid behaviour when there's no coverage

### ISSUE THREAD

**Issue by DougBurke** [cxcsds/ciao-contrib#883]
Why am I seeing this error message:

```
% find_chandra_obsid "a2472" v=4
Running: find_chandra_obsid
  version: 06 January 2023
Querying name resolvers for name=a2472
Found ra=340.47375 dec=17.54166667
    = 22h 41m 53.69999999999294s 17d 32' 30.000012000005256"
Querying Chandra archive for ra=340.47375 dec=17.54166667 radius=0.016666666666666666 inst=all grat=all
Retrieving URL: https://cxcfps.cfa.harvard.edu/cgi-bin/cda/footprint/get_vo_table.pl?strict=1&POS=340.47375,17.54166667&SIZE=0.016666666666666666 timeout=None
Search returned 0 rows
Chandra search found 0 results
After removing duplicates, have 0 matches
# find_chandra_obsid (06 January 2023): ERROR max() arg is an empty sequence
```

It should error out better than this. What has changed?

**Comment by DougBurke** [comment]
Argh

```
% find_chandra_obsid 'ngc 2242' --debug
# find_chandra_obsid (06 January 2023): ERROR max() arg is an empty sequence


##### Traceback:

Traceback (most recent call last):
  File "/lagado2.real/local/anaconda/envs/ciao417/lib/python3.11/site-packages/ciao_contrib/logger_wrapper.py", line 560, in new_fn
    return fn(*args, **kw)
           ^^^^^^^^^^^^^^^
  File "/lagado2.real/local/anaconda/envs/ciao417/bin/find_chandra_obsid", line 596, in fco
    run_fco(opts)
  File "/lagado2.real/local/anaconda/envs/ciao417/bin/find_chandra_obsid", line 569, in run_fco
    display_obsinfo(ra, dec, obsinfo, detail=opts["detail"])
  File "/lagado2.real/local/anaconda/envs/ciao417/bin/find_chandra_obsid", line 224, in display_obsinfo
    pilen = max_len(obsinfo['piname'])
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lagado2.real/local/anaconda/envs/ciao417/bin/find_chandra_obsid", line 154, in max_len
    return max(len(s) for s in array)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: max() arg is an empty sequence
```
