### ISSUE TITLE
add mkosip to runtool

### ISSUE THREAD

**Issue by kglotfelty** [cxcsds/ciao-contrib#906]
I'm sure it'll get added automagically at some point but just a reminder to be sure `mkosip` gets added to the `runtool` module.

**Comment by DougBurke** [comment]
```
>>> from ciao_contrib import runtool
>>> runtool.mkosip
<CIAO tool: mkosip>
>>> runtool.mkosip()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dburke/ciao/ciao-contrib/ciao_contrib/runtool.py", line 1863, in __call__
    raise IOError(f"An error occurred while running '{self._toolname}':{sep}{smsg}")
OSError: An error occurred while running 'mkosip':
  terminate called after throwing an instance of 'std::runtime_error'
    what():  Either p2resp_file/gain_file or obspar need to be specified.
```

What a glorious error message ....

It may need updating, but we have a copy in now.

**Comment by kglotfelty** [comment]
There is so, so much wrong (ie inconsistent w/ existing norms) with `mkosip` ; error reporting is just start.
